name: dotnet format --check
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Install dotnet-format
        run: |
          dotnet tool install -g dotnet-format

      - name: Check indent
        run: |
          dotnet format ./ProkenB/Assets/Scripts -f --check
