name: dotnet format --check
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Restore vprEn2Fr (Windows)
        run: |
          dotnet format ./ProkenB/Assets/Scripts -f --check
